### ISSUE TITLE
trailing / on image URL, get 404

### ISSUE THREAD

**Issue by jrmineur** [adhamenaya/PopularMovieMVP#2]
Nice implementation of the Popular Movies app.   While compiling and browsing your implementation, I didn't get any images downloaded.   The image.tmdb.org fetch was throwing a 404 error.

I fixed this in utils/Util.java by stripping out the trailing "/".

    /**
     * Get the full path of the image
     */
    public static String getImagePath(String imageName) {
    //   return imageBaseUrl + imageSize + imageName + "/";
        return imageBaseUrl + imageSize + imageName;

Cheers and thanks for sharing your version of this implementation!

**Comment by adhamenaya** [comment]
@jrmineur .. it's a pleasure you find ti useful!!
